environment: prod
servers:
  grpc:
    host: ""
    port: 50051
    timeout: 5s
  http:
    host: ""
    port: 8080
    timeout: 5s
connections:
  postgres:
    username: playlists_user
    password: "12345678"
    host: postgres
    port: 5432
    dbName: playlists
    sslEnabled: disable
  redis:
    host: localhost
    port: 6379
  s3:
    endpoint: minio:9000
    accessKey: <your_access_key>
    secretKey: <your_secret_key>
    useSsl: false
    coversBucket: covers
  songs:
    host: songs
    port: 5050
    retries: 5
    timeout: 5s
secrets:
  public: VBco3QN3RVq1ebse8SJaYhqV4fKPqQxjyT/LEmFs+U0=