// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type LikedPlaylist struct {
	LikedPlaylist uuid.UUID
	UserID        uuid.UUID
	LikedAt       time.Time
}

type LikedTrack struct {
	UserID  uuid.UUID
	TrackID uuid.UUID
	LikedAt time.Time
}

type Playlist struct {
	ID         uuid.UUID
	Title      string
	AuthorID   uuid.UUID
	CoverUrl   pgtype.Text
	TrackIds   []uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  pgtype.Timestamptz
	ReleasedAt pgtype.Timestamptz
	IsAlbum    bool
	IsPublic   bool
}
