with-expecter: True
dir: "internal/mocks/{{.PackageName}}"
keeptree: False
mockname: "{{.InterfaceName}}"
filename: "{{.InterfaceName}}.go"
outpkg: "{{.PackageName}}mocks"
all: True
packages:
  github.com/Benzogang-Tape/audio-hosting/playlists/internal/service/covers:
  github.com/Benzogang-Tape/audio-hosting/playlists/internal/service/playlists: