version: "3"

tasks:
  protoc:
    desc: "generate go files from protos"
    cmds:
      - protoc --go_out=./api/protogen --go_opt=paths=source_relative --go-grpc_out=./api/protogen --go-grpc_opt=paths=source_relative ./api/*.proto
      - mv ./api/protogen/api/* ./api/protogen
      - rmdir ./api/protogen/api
